# Generated by Django 3.1.4 on 2021-01-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outside_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('purpose', models.CharField(max_length=150)),
                ('phone_no', models.IntegerField(default='0')),
                ('time_of_entry', models.TimeField(auto_now=True)),
                ('time_of_exit', models.TimeField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('picture', models.ImageField(blank=True, upload_to='outside_img/')),
            ],
        ),
    ]
