# Generated by Django 3.1.4 on 2021-01-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outside_person',
            name='time_of_exit',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
