# Generated by Django 3.1.4 on 2021-01-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0002_auto_20210107_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='outside_person',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
