# Generated by Django 3.1.4 on 2021-01-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0003_outside_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outside_person',
            name='email',
            field=models.EmailField(blank=True, default='None', max_length=50),
        ),
    ]
