# Generated by Django 3.1.7 on 2021-04-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0004_auto_20210107_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outside_person',
            old_name='picture',
            new_name='photo',
        ),
    ]
