# Generated by Django 3.1.7 on 2021-04-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0005_auto_20210429_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outside_person',
            name='photo',
            field=models.ImageField(upload_to='outside_img/'),
        ),
    ]
