# Generated by Django 3.1.4 on 2021-01-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=122)),
                ('date_of_birth', models.DateField()),
                ('deaprtment', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=6)),
                ('university_mail', models.CharField(max_length=20)),
                ('date_of_joining', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to='employee_img/')),
                ('id_proof_no', models.CharField(max_length=20)),
                ('id_type', models.CharField(max_length=20)),
                ('id_photo', models.ImageField(blank=True, upload_to='employee_id/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=122)),
                ('time_of_entry', models.TimeField(auto_now=True)),
                ('time_of_exit', models.TimeField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
