# Generated by Django 3.1.4 on 2021-01-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=122)),
                ('course', models.CharField(max_length=10)),
                ('course_years', models.IntegerField()),
                ('school', models.CharField(max_length=6)),
                ('dept', models.CharField(max_length=5)),
                ('roll_no', models.CharField(max_length=20)),
                ('university_mail', models.EmailField(max_length=254)),
                ('mentors_name', models.CharField(max_length=122)),
                ('date_of_admission', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to='student_img/')),
                ('parents_name', models.CharField(max_length=122)),
                ('parents_no', models.IntegerField(default='0')),
                ('parents_email', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('id_proof_no', models.CharField(max_length=20)),
                ('id_type', models.CharField(max_length=20)),
                ('id_photo', models.ImageField(blank=True, upload_to='student_id/')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20)),
                ('reg_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=122)),
                ('time_of_entry', models.TimeField(auto_now=True)),
                ('time_of_exit', models.TimeField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
