# Generated by Django 3.1.7 on 2021-04-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_years',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_admission',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_proof_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_type',
        ),
    ]
